version: "3"

services:
  compiler-explorer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: madduci/docker-compiler-explorer:latest
    container_name: compiler-explorer
    ports:
      - 10240:10240
    networks:
      - ce_network
    restart: on-failure
    stop_grace_period: 1m30s

networks: 
  ce_network: